# Generated by Django 5.2.1 on 2025-05-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('poste', models.CharField(max_length=100)),
                ('candidats_vus', models.ManyToManyField(blank=True, related_name='recruteurs_interesses', to='candidats.candidat')),
            ],
        ),
    ]
